name: Cookie Cutter

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project'
        required: true
        type: string
        default: 'Test'
      new_repo_visibility:
        description: 'Visibility of the new GitHub repository'
        required: true
        type: choice
        options:
          - public
          - private
        default: 'public'

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: Define Cookiecutter Inputs
        run: |
          echo "default_context:" > cookiecutter_inputs.yml
          echo "  project_name: \"${{ inputs.project_name }}\"" >> cookiecutter_inputs.yml
          echo "  author_name: \"${{ inputs.author_name }}\"" >> cookiecutter_inputs.yml

          
          cat cookiecutter_inputs.yml

      - name: Generate Project with Cookiecutter
        id: generate_project
        run: |
          PROJECT_SLUG="${{ inputs.project_name }}"
          
          cookiecutter "https://github.com/abrar2204/CookieCutter" \
            --no-input \
            --config-file cookiecutter_inputs.yml \
            --output-dir "./generated_project_temp" \
            --overwrite-if-exists
          
          echo "project_slug=$PROJECT_SLUG" >> $GITHUB_OUTPUT
          echo "GENERATED_DIR=./generated_project_temp/$PROJECT_SLUG" >> $GITHUB_OUTPUT
          
      - name: Install tree command
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Display Generated Project Structure
        run: |
          GENERATED_PROJECT_PATH="${{ steps.generate_project.outputs.GENERATED_DIR }}"
          echo "::group::Generated Project Structure for $GENERATED_PROJECT_PATH"
          tree -L 3 -a -F --dirsfirst "$GENERATED_PROJECT_PATH"
          echo "::endgroup::"

      - name: Navigate to Generated Project Directory
        run: |
          echo "Navigating to ${{ steps.generate_project.outputs.GENERATED_DIR }}"
          cd "${{ steps.generate_project.outputs.GENERATED_DIR }}"

      - name: Initialize Git in the Generated Project
        run: |
          git init
          git branch -m main
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Initial commit for ${{ inputs.project_name }} generated by Cookiecutter" || echo "No changes to commit initially."

      - name: Create New GitHub Repository (Using GitHub CLI)
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_FOR_NEW_REPOS }}
        run: |
          sudo apt-get update
          sudo apt-get install gh -y
          
          REPO_NAME="${{ inputs.project_name }}"
          echo "Creating new GitHub repository: $REPO_NAME with visibility ${{ inputs.new_repo_visibility }}"
          
          if [[ "${{ inputs.new_repo_visibility }}" == "public" ]]; then
            gh repo create "$REPO_NAME" --public --description "Generated .NET project: ${{ inputs.project_name }}" || true
          else
            gh repo create "$REPO_NAME" --private --description "Generated .NET project: ${{ inputs.project_name }}" || true
          fi
          
          REPO_URL="https://github.com/${{ github.repository_owner }}/$REPO_NAME"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV

      - name: Add Remote and Push to New Repository
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | \
            xargs -L1 git config --unset-all
          
          git remote add origin ${{ env.REPO_URL }}.git
          
          git push -u origin main
        env:
          GIT_ASKPASS: "echo ${{ secrets.GH_PAT_FOR_NEW_REPOS }}"
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_NEW_REPOS }} 

      - name: Clean Up Generated Temp Directory (Optional)
        run: |
          cd "${{ github.workspace }}"
          rm -rf generated_project_temp